BaseUrl: "https://lacnotredame.org/"
ContentDir: "content"
LayoutDir: "layouts"
PublishDir: "public"
BuildDrafts: true
languageCode: "en-us"
Title: "Lac Notre-Dame and Usher Lake Association"
PluralizeListTitles: False
googleAnalytics: ""
menu:
 
Params:
  Author: "Lac Notre-Dame executives"
  Banner: "Lac Notre-Dame and Usher Lake Association"
  DateForm: "2006-01-02"
  disqusShortname: ""
  Search: "lacnotredame.org"
  ShowRelatedPost: True
  Slogan: ""
  ISO8601: "2006-01-02T15:04:05Z07:00"
  copyright: "lacnotredame.org"
  logo: "/lacnotredame-logo.png"
taxonomies:
  tag: "tags"
permalinks:
  post: /post/:year/:slug/
MetadataFormat: "yaml"
theme: "bootstrapfour"
sitemap:
  changefreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"